[watch]
watch = ["src", "Cargo.toml", "index.html"]

[serve]
no_autoreload = true

[[proxy]]
backend = "http://localhost:3000/proxy"

[[hooks]]
stage = "post_build"
command = "cargo"
command_arguments = ["run", "-p", "utils", "--bin", "post_build"]