name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - run: cargo test
    - run: wasm-pack test --headless --chrome
    - uses: jetli/trunk-action@v0.1.0
      with:
        # Optional version of trunk to install(eg. 'v0.8.1', 'latest')
        version: 'latest'
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: trunk build, cargo build -p utils --bin server
        start: cargo run -p utils --bin server
        wait-on: "http://localhost:8080"
        wait-on-timeout: 120